[package]
name = "tlse_sys"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[dependencies.winapi]
version = "0.3.9"
features = [ "minwindef", "ntdef", "winnt", "memoryapi", "processthreadsapi", "psapi", "consoleapi", "wincon", "winuser", "d3d9" ]